name: 'Inject command action'
description: 'Inject the output of a command into a file of your repo'
branding:
  icon: 'file-plus'
  color: 'white'
inputs:
  command:
    description: 'Command to execute'
    required: true
  target:
    description: 'Relative path to the local file you want to modify'
    required: true
  pattern:
    description: 'Pattern to identify where and what to replace in the target file'
    default: ''
  force:
    description: 'Append at the bottom of the target file if the pattern is not found'
    default: true
outputs:
  debug:
    description: 'debug output'
  debug2:
    description: 'debug output'
  pattern:
    description: 'Pattern used for the replacement (useful to debug)'
  file_changed:
    description: 'Relative path of the file that has changed'
runs:
  using: 'node12'
  main: 'dist/index.js'
