name: 'tests'
on: push

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          url: https://raw.githubusercontent.com/olivr-com/inject-command-action/master/test.md
          target: README.md
